export const
  GET_TALENT = 'GET_TALENT',
  GET_TALENT_SUCCESS = 'GET_TALENT_SUCCESS',
  GET_TALENT_FAIL = 'GET_TALENT_FAIL',
  GET_PARTNERS = 'GET_PARTNERS',
  GET_PARTNERS_SUCCESS = 'GET_PARTNERS_SUCCESS',
  GET_PARTNERS_FAIL = 'GET_PARTNERS_FAIL',
  GET_GENERAL = 'GET_GENERAL',
  GET_GENERAL_SUCCESS = 'GET_GENERAL_SUCCESS',
  GET_GENERAL_FAIL = 'GET_GENERAL_FAIL',
  GET_CONNECTIONS = 'GET_CONNECTIONS',
  GET_CONNECTIONS_SUCCESS = 'GET_CONNECTIONS_SUCCESS',
  GET_CONNECTIONS_FAIL = 'GET_CONNECTIONS_FAIL';
